// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Admin struct {
	ID       string `json:"_id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Character struct {
	ID        string `json:"_id"`
	Name      string `json:"name"`
	ImageLink string `json:"imageLink"`
}

type NewAdmin struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type NewPlayer struct {
	Username string `json:"username"`
	Rating   *int   `json:"rating"`
	Score    *int   `json:"score"`
}

type Player struct {
	ID        string  `json:"_id"`
	Slug      string  `json:"slug"`
	Username  string  `json:"username"`
	Rating    int     `json:"rating"`
	Score     int     `json:"score"`
	Country   *string `json:"country"`
	Twitter   *string `json:"twitter"`
	Twitch    *string `json:"twitch"`
	Instagram *string `json:"instagram"`
	RealName  *string `json:"realName"`
}
